### ISSUE TITLE
Error in running Baseline-Inference.ipynb

### ISSUE THREAD

**Issue by ahmed-fau** [microsoft/PLC-Challenge#1]
Hi,
I am trying to run the baseline PLC model using the notebook _Baseline-Inference.ipynb_  and the last cell gives the following error:

```
---------------------------------------------------------------------------
AxisError                                 Traceback (most recent call last)
Input In [43], in <module>
      9 loss_mask = np.loadtxt(lost_file)
     11 feats, feats_recon = build_features_logspec_plcmask(data, loss_mask)
---> 12 feats = np.array(feats).swapaxes(0, 1)
     13 feats = feats.reshape(feats.shape[0], -1)
     15 feats_recon = np.array(feats_recon).swapaxes(0, 1)

AxisError: axis2: axis 1 is out of bounds for array of dimension 1
```

Any idea what causes this problem?
Many thanks in advance!

**Comment by halcy** [comment]
That's weird - can you send me the files (wav + is_lost.txt) that it errors on?

**Comment by ahmed-fau** [comment]
I have just selected one wave+is_lost.txt item from the blind set. It seems that the function `build_features_logspec_plcmask` returns two lists of `np.array` objects with the first one of length = 5 and the second one of length 3 and there is no second axis for these two lists (i.e., each of them is 1d)

**Comment by halcy** [comment]
Hm. It seems to work for me, maybe it is a versioning issue. The dimensionality here should be something like (5, number of frames, 161) before the swapaxes. I have added a requirements.txt, can you try with that and in a python 3 environment and let me know if this works?

**Comment by ahmed-fau** [comment]
> The dimensionality here should be something like (5, number of frames, 161) before the swapaxes

Alright, it seems like there was a change I did unintentionally to the input files that causes the dimensionality yo be only (5,). Now it sounds to work properly. Thanks a lot for the prompt reply.

**Comment by ahmed-fau** [comment]
@halcy I could reconstruct the dataset with this baseline model but the reconstructions sound to be even worse than the zero-fill case (at least with PESQ scores). Is this normal? Could you provide one sample reconstruction form this baseline model so that I can verify it's not a generation problem?

**Comment by breizhn** [comment]
I encountered the same. Here are the metrics:
| Type | STOI | SI-SDR | PESQ | PLC-MOS |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| Unprocessed | 0.835 | 11.09 | 2.185 | 2.874
| Baseline | 0.809 | -0.423 | 2.047 | 2.766

They are all worse than the unprocessed signal.

**Comment by halcy** [comment]
That is correct - this model is very much on the low end of possible models and does not do many things that a sensible model should probably do, and we did not spend time trying to make it a good model. I only did a brief test on the blind set, where it was a mix between worse for some metrics (DNSMOS, STOI, PESQ), better for others (DNSMOS835, MCD), and statistically indistinguishable for one (PLCMOS).
