### ISSUE TITLE
PLC MOS API access problem

### ISSUE THREAD

**Issue by Niteshkumarchaudhary** [microsoft/PLC-Challenge#2]
Hi,
We got the token but unable to access the PLC-MOS-API-Example.ipynb script. It throws **JSONDecodeError: Expecting value: line 1 column 1 (char 0)** when running last line script **resp.json()** in the example. Please help 

With regards,
Nitesh

**Comment by halcy** [comment]
Hi,

the token was not active yet. It is now active (or will be in a few minutes). Please be aware that the API is, unfortunately, currently somewhat slow. We're working on getting the onnx model released for PLCMOS so you could run it yourself, but this may still take a bit.

Best,
Lorenz

**Comment by Niteshkumarchaudhary** [comment]
Hi, Is there any certificate (.pem) file as we still getting same error when processing on our cloud platform ?
