### ISSUE TITLE
PLC MOS API access problem v1

### ISSUE THREAD

**Issue by Niteshkumarchaudhary** [microsoft/PLC-Challenge#3]
Hi, Is there any certificate (.pem) file as we still getting same error when processing on our cloud platform ?

Hi,

the token was not active yet. It is now active (or will be in a few minutes). Please be aware that the API is, unfortunately, currently somewhat slow. We're working on getting the onnx model released for PLCMOS so you could run it yourself, but this may still take a bit.

Best,
Lorenz

_Originally posted by @halcy in https://github.com/microsoft/PLC-Challenge/issues/2#issuecomment-1060486208_

**Comment by halcy** [comment]
If you have pasted in your username and token, it should work - nothing additional is required. Alternatively, we have now released our current PLCMOS as an onnx model, so you can try using it locally - please have a look, maybe that helps you do the evaluations you need to do!
