### ISSUE TITLE
Very limited download speed for training and testing datasets

### ISSUE THREAD

**Issue by jmlemercier** [microsoft/PLC-Challenge#5]
Hi, 
I am trying to download the open-source training and testing challenge data. However the download speed is surprisingly low (less than 1Mbps) although my personal downalod speed is much higher than that (around 800Mbps). Is there a specific reason for that? 
Given the size of the tar archive (10GB) it means one must wait somewhat 4 hours for the download to complete, and it seems the server closes the connection with a timeout inferior to that, causing the download to fail.

Any help is welcome, thanks

**Comment by halcy** [comment]
The data is stored in an Azure storage blob container. When trying it myself right now, I get ~4Mb/s, which is quicker, but also still quite limited. I will have a look if there is some limit on the egress speed and if so, see if I can raise it.

**Comment by halcy** [comment]
I changed some settings, and allowed download without HTTPS enabled (changed the links in the README) which has made the speed a tiny bit better, but it's still just around 5 to 6 megabytes per second. I'm afraid that's because we're just using a regular, non-premium azure blob storage container for this, and that's about the limit, so this is about as fast as it will get.

**Comment by halcy** [comment]
If you still have trouble downloading it, let me know, I can split the dataset into multiple archives - or you could use some tool that can resume (wget -c or somesuch), that should be supported

**Comment by jmlemercier** [comment]
Hi Halcy, thanks for the answer, unfortunately the download speed didn't seem to change much: I'll use the continuing option of wget and let you know if I have further problems.

**Comment by jmlemercier** [comment]
Well, even with the -c flag it seems not to be able to retrieve the packets. Since it seems to fail past 1GB, I 'd really appreciate if you can split in ~10 archives, thanks a lot !

**Comment by halcy** [comment]
I have created a multipart zip download, and put the links in the README: https://github.com/microsoft/PLC-Challenge/blob/main/README.md

Please let me know if you have any further problems.

**Comment by jmlemercier** [comment]
All good thanks!
